server:
  port: 3000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-config-server
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lxiaobai223/aigou-config.git
          username: qianlian9937@163.com
          password: 770104583.com
#        native:
#          search-locations: C:/Users/Administrator/Desktop/aigou/lxb/aigou-config
