server:
  port: 1000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

spring:
  application:
    name: eureka-server
