server:
  port: 1000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
  instance:
      prefer-ip-address: true #使用ip注册
spring:
  application:
    name: eureka-server
