server:
  port: 4000

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true #使用ip注册
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/** #平台服务的请求路径
      serviceId: plat-service
  prefix: /services #请求前缀
spring:
  application:
    name: zuul